CREATE TABLE [stg].[financeSales] (
    [Document No_]                    NVARCHAR (20)    NULL,
    [Document Line No_]               NVARCHAR (20)    NULL,
    [is_Adjustment]                   BIT              NULL,
    [keyInvoiceDate]                  DATE             NULL,
    [last_entry]                      INT              NULL,
    [_salesInvoice]                   TINYINT          NULL,
    [_amazonShipment]                 BIT              NULL,
    [_creditMemo]                     BIT              NULL,
    [Location]                        NVARCHAR (10)    NULL,
    [keyCustomer]                     NVARCHAR (20)    NULL,
    [ShipToCode]                      NVARCHAR (10)    NULL,
    [keySKU]                          NVARCHAR (20)    NULL,
    [keyChannel]                      NVARCHAR (10)    NULL,
    [keyCampaign]                     NVARCHAR (20)    NULL,
    [keyMedia]                        NVARCHAR (10)    NULL,
    [dgdOrderDate]                    DATE             NULL,
    [Legal Entity]                    NVARCHAR (20)    NULL,
    [Reporting Group]                 NVARCHAR (50)    NULL,
    [VAT Business Group]              NVARCHAR (10)    NULL,
    [VAT Product Group]               NVARCHAR (10)    NULL,
    [Quantity]                        DECIMAL (38, 20) NULL,
    [Cost Posted]                     DECIMAL (38, 20) NULL,
    [Total Discount Amount (LCY)]     DECIMAL (38, 20) NULL,
    [Promotion Discount Amount (LCY)] DECIMAL (38, 20) NULL,
    [System Discount Amount (LCY)]    DECIMAL (38, 20) NULL,
    [Manual Discount Amount (LCY)]    DECIMAL (38, 20) NULL,
    [Gross Sales Amount (LCY)]        DECIMAL (38, 20) NULL,
    [Net Sales Amount (LCY)]          DECIMAL (38, 20) NULL,
    [_RRP]                            DECIMAL (38, 20) NULL,
    [keyCountryCode]                  NVARCHAR (10)    NULL,
    [Original Currency]               NVARCHAR (10)    NULL,
    [Gross Sales Amount (FCY)]        DECIMAL (38, 20) NULL,
    [Net Sales Amount (FCY)]          DECIMAL (38, 20) NULL,
    [Total Discount Amount (FCY)]     DECIMAL (38, 20) NULL,
    [Promotion Discount Amount (FCY)] DECIMAL (38, 20) NULL,
    [Manual Discount Amount (FCY)]    DECIMAL (38, 20) NULL,
    [System Discount Amount (FCY)]    DECIMAL (38, 20) NULL
);
GO
