CREATE TABLE [stg].[oos_plr] (
    [id]                   INT              NULL,
    [location_id]          INT              NULL,
    [is_batch]             BIT              DEFAULT ((0)) NULL,
    [is_po]                BIT              DEFAULT ((0)) NULL,
    [is_to]                BIT              DEFAULT ((0)) NULL,
    [is_qa]                BIT              DEFAULT ((0)) NULL,
    [is_actual]            BIT              DEFAULT ((0)) NULL,
    [is_oos]               BIT              DEFAULT ((0)) NULL,
    [ref]                  INT              NULL,
    [ldd]                  DATE             NULL,
    [erd]                  DATE             NULL,
    [sale_first]           DATE             NULL,
    [sale_last]            DATE             NULL,
    [sales_2day]           INT              DEFAULT ((0)) NULL,
    [sale_total]           INT              DEFAULT ((0)) NULL,
    [subs_total]           INT              DEFAULT ((0)) NULL,
    [open_balance]         INT              DEFAULT ((0)) NULL,
    [avail_balance]        INT              DEFAULT ((0)) NULL,
    [ring_fenced]          INT              DEFAULT ((0)) NULL,
    [not_rf_subs_reserve]  INT              DEFAULT ((0)) NULL,
    [ring_fence_deadline]  DATE             NULL,
    [on_order]             INT              DEFAULT ((0)) NULL,
    [estimated_lost_subs]  INT              DEFAULT ((0)) NULL,
    [estimate_cycle]       INT              DEFAULT ((0)) NULL,
    [estimate_daily_sales] DECIMAL (28, 10) NULL,
    [estimate_total_sales] INT              NULL,
    [estimate_close_bal]   INT              DEFAULT ((0)) NULL,
    [estimate_open_date]   DATE             NULL,
    [estimate_close_date]  DATE             NULL,
    [forecast_cycle]       INT              DEFAULT ((0)) NULL,
    [forecast_daily_sales] DECIMAL (28, 10) NULL,
    [forecast_total_sales] INT              NULL,
    [forecast_close_bal]   INT              DEFAULT ((0)) NULL,
    [forecast_open_date]   DATE             NULL,
    [forecast_close_date]  DATE             NULL,
    [is_end]               BIT              DEFAULT ((0)) NULL
);
GO
