CREATE TABLE [ext].[vw_Item_PLR_Historical_static] (
    [Closing Date]                  DATE            NOT NULL,
    [Country]                       NVARCHAR (50)   NOT NULL,
    [Distribution Type]             NVARCHAR (50)   NOT NULL,
    [Inventory Posting]             NVARCHAR (50)   NULL,
    [Current Stock State]           VARCHAR (20)    NOT NULL,
    [Stock State End of Week]       VARCHAR (23)    NOT NULL,
    [Stock State End of Month]      VARCHAR (23)    NOT NULL,
    [Item Range]                    NVARCHAR (50)   NOT NULL,
    [Item Code]                     NVARCHAR (32)   NOT NULL,
    [Item Description]              NVARCHAR (50)   NOT NULL,
    [Last Updated]                  NVARCHAR (4000) NULL,
    [Batch Number]                  NVARCHAR (32)   NOT NULL,
    [Expiration Date]               DATETIME        NULL,
    [Latest Despatch Date]          DATETIME        NULL,
    [Weeks Remaining]               INT             NULL,
    [Months Remaining]              INT             NULL,
    [Unit Cost]                     DECIMAL (12, 6) NOT NULL,
    [Batch Quantity]                INT             NOT NULL,
    [Average Daily Sales]           DECIMAL (9, 3)  NULL,
    [Stock at Risk Quantity]        INT             NOT NULL,
    [Stock at Risk Value]           MONEY           NULL,
    [Expiration EOM]                VARCHAR (3)     NOT NULL,
    [Expiration EOW]                VARCHAR (3)     NOT NULL,
    [Latest Despatch EOM]           VARCHAR (3)     NOT NULL,
    [Latest Despatch EOW]           VARCHAR (3)     NOT NULL,
    [6 Month Window]                VARCHAR (3)     NOT NULL,
    [Stock at Risk]                 VARCHAR (3)     NOT NULL,
    [Item Status]                   VARCHAR (29)    NOT NULL,
    [Sales Lifespan]                VARCHAR (29)    NOT NULL,
    [Batch Time Left]               VARCHAR (20)    NOT NULL,
    [Low Risk & New]                VARCHAR (3)     NOT NULL,
    [last_updated_sort]             DATETIME2 (1)   NULL,
    [Current Stock State_sort]      INT             NOT NULL,
    [Stock State End of week_sort]  INT             NOT NULL,
    [Stock State End of month_sort] INT             NOT NULL,
    [Sales Lifespan_sort]           INT             NOT NULL,
    [Batch Time Left_sort]          INT             NOT NULL
);
GO
